### ISSUE TITLE
课表功能非常赞，再修复一些小细节就更完美了

### ISSUE THREAD

**Issue by deelters** [nonesrc/roach#13]
1. 第9、10、11节选修课显示问题
2. 教学周单/双周显示
3. 单堂课的显示问题

**Comment by zRains** [comment]
OK，安排上了。

![HE@ S1U07LRH{WKT3AM5ISR](https://user-images.githubusercontent.com/16508606/158537378-290a7f00-e9a5-4b20-894d-c97ebd626385.png)
![O![HE@ S1U07LRH{WKT3AM5ISR](https://user-images.githubusercontent.com/16508606/158537378-290a7f00-e9a5-4b20-894d-c97ebd626385.png)
(SF50A AIA{KF~YR11 R](https://user-images.githubusercontent.com/16508606/158537408-386375b9-cd46-4b08-8048-08565ddbff61.png)

**Comment by zRains** [comment]
#14 修复
